plugins:
  - "prettier-plugin-solidity"
printWidth: 120
trailingComma: "all"
endOfLine: "lf"
semi: true
singleQuote: false
tabWidth: 2
useTabs: false

overrides:
  - files: "*.md"
    options:
      proseWrap: "always"
      printWidth: 80
  - files: "*.sol"
    options:
      compiler: "0.8.27"
      parser: "slang"
      tabWidth: 4
  - files: "*.json"
    options:
      printWidth: 200

